# Generated by Django 3.1.3 on 2020-12-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
